name: First GitHub Actions Workflow

on:
  push:

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Hello from GitHub Actions"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
